"""create rigs and wells tables

Revision ID: f5f545da15a8
Revises: 1f4dfb9fc177
Create Date: 2026-08-15 10:33:20.958767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f545da15a8'
down_revision: Union[str, None] = '1f4dfb9fc177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rigs_name'), 'rigs', ['name'], unique=True)
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('spud_date', sa.Date(), nullable=True),
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rig_id'], ['rigs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wells_name'), 'wells', ['name'], unique=True)
    op.create_index(op.f('ix_wells_rig_id'), 'wells', ['rig_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wells_rig_id'), table_name='wells')
    op.drop_index(op.f('ix_wells_name'), table_name='wells')
    op.drop_table('wells')
    op.drop_index(op.f('ix_rigs_name'), table_name='rigs')
    op.drop_table('rigs')
    # ### end Alembic commands ###
