"""create operations tables

Revision ID: fcf67d5f1303
Revises: f5f545da15a8
Create Date: 2026-08-15 10:58:36.700459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf67d5f1303'
down_revision: Union[str, None] = 'f5f545da15a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_readings_well_id'), 'operation_readings', ['well_id'], unique=False)
    op.create_table('threshold_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threshold_alerts_created_at'), 'threshold_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_threshold_alerts_well_id'), 'threshold_alerts', ['well_id'], unique=False)
    op.create_table('threshold_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('warning_min', sa.Float(), nullable=True),
    sa.Column('warning_max', sa.Float(), nullable=True),
    sa.Column('critical_min', sa.Float(), nullable=True),
    sa.Column('critical_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id', 'metric', name='uq_threshold_well_metric')
    )
    op.create_index(op.f('ix_threshold_configs_well_id'), 'threshold_configs', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threshold_configs_well_id'), table_name='threshold_configs')
    op.drop_table('threshold_configs')
    op.drop_index(op.f('ix_threshold_alerts_well_id'), table_name='threshold_alerts')
    op.drop_index(op.f('ix_threshold_alerts_created_at'), table_name='threshold_alerts')
    op.drop_table('threshold_alerts')
    op.drop_index(op.f('ix_operation_readings_well_id'), table_name='operation_readings')
    op.drop_table('operation_readings')
    # ### end Alembic commands ###
